kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkinstestnew
  labels:
    app: jenkinstestnew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkinstestnew
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: jenkinstestnew
      labels:
        app: jenkinstestnew
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "jenkinstestnew"
     #  port is required if you have service running, else comment it
        dapr.io/app-port: "8090"
        dapr.io/config: "appconfig"
    spec:
     containers:
     - name: jenkinstestnew
       image: ghcr.io/prasantabarik/jenkins-pipeline/jenkins-pipeline:latest
       imagePullPolicy: Always
       resources:
         requests:
           memory: 250Mi
           cpu: 200m
         limits:
           memory: 500Mi
           cpu: 250m
     imagePullSecrets:
      - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: jenkinstestnew
  labels:
    app: jenkinstestnew
spec:
  type: LoadBalancer
  ports:
  - port: 8090
  selector:
    app: jenkinstestnew
